name: flutter_metronome
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.2
  syncfusion_flutter_core: ^30.1.38
  syncfusion_flutter_sliders: ^30.1.38
  just_audio: ^0.10.4
  path_provider: ^2.1.5
  lottie: ^3.3.1
  google_fonts: ^6.2.1
  wheel_picker: ^0.2.2
  shared_preferences: ^2.5.3
  webview_flutter: ^4.13.0
  go_router: ^16.0.0
  provider: ^6.1.5
  gpt_markdown: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/test/
    - assets/lottie/
    - assets/google_fonts/